name: 'panfit-backend'

services:
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - path: .env
        required: true
    environment:
      - PYTHONPATH=/opt
      - MAIN_FOLDER=/opt/
      - MODE=development
    ports:
      - "8083:5000"
    volumes:
      - ./src:/opt/src
    networks:
      - panfit_network
networks:
  panfit_network:
    driver: bridge
