POST http://localhost:8083/product
Content-Type: application/json

{
    "name":"Bolo de Tapioca",
    "wheight":500.00,
    "category":"Bolos",
    "receipe":"674cb132b818139c23d44e86",
    "sale_price":154.31
}

