POST http://localhost:5000/product
Content-Type: application/json

{
    "category":"receitas de bolo",
    "items":[
        {
            "id":"85ba135f55e12684a8c0fc52",
            "wheight":10.0
        },
        {
            "id":"85ba135f55e12684a8c0fc50",
            "wheight":30.0
        },
        {
            "id":"85ba135f55e12684a8c0fc60",
            "wheight":20.0
        }
    ]
}