POST http://localhost:8083/receipe
Content-Type: application/json

{
    "category":"receitas de bolo",
    "items":[
        {
            "id":"674c8a98e4849ec3ff666ac7",
            "wheight":10.0
        },
        {
            "id":"674cb09bb818139c23d44e85",
            "wheight":30.0
        }
    ]
}