POST http://localhost:8083/item
Content-Type: application/json

{
    "name":"Bolacha maizena coisa boa",
    "GTIN":"53890432949323",
    "wheight":500.00,
    "category":"Bolachas",
    "quantity":50
}